/**
 * ISO 3166-1 alpha-2 -> [numeric-3, English name] lookup. Generated from
 * i18n-iso-countries (a dev-only dependency) - do not edit by hand. Used by
 * <WorldMap> to join alpha-2 country codes (from cf-ipcountry / GeoIP) to the
 * numeric ids of the world-atlas topojson, and to label the tooltip.
 */
export const ISO_A2: Record<string, [numeric: string, name: string]> = {
  AF: ['004', "Afghanistan"],
  AL: ['008', "Albania"],
  DZ: ['012', "Algeria"],
  AS: ['016', "American Samoa"],
  AD: ['020', "Andorra"],
  AO: ['024', "Angola"],
  AI: ['660', "Anguilla"],
  AQ: ['010', "Antarctica"],
  AG: ['028', "Antigua and Barbuda"],
  AR: ['032', "Argentina"],
  AM: ['051', "Armenia"],
  AW: ['533', "Aruba"],
  AU: ['036', "Australia"],
  AT: ['040', "Austria"],
  AZ: ['031', "Azerbaijan"],
  BS: ['044', "Bahamas"],
  BH: ['048', "Bahrain"],
  BD: ['050', "Bangladesh"],
  BB: ['052', "Barbados"],
  BY: ['112', "Belarus"],
  BE: ['056', "Belgium"],
  BZ: ['084', "Belize"],
  BJ: ['204', "Benin"],
  BM: ['060', "Bermuda"],
  BT: ['064', "Bhutan"],
  BO: ['068', "Bolivia"],
  BA: ['070', "Bosnia and Herzegovina"],
  BW: ['072', "Botswana"],
  BV: ['074', "Bouvet Island"],
  BR: ['076', "Brazil"],
  IO: ['086', "British Indian Ocean Territory"],
  BN: ['096', "Brunei Darussalam"],
  BG: ['100', "Bulgaria"],
  BF: ['854', "Burkina Faso"],
  BI: ['108', "Burundi"],
  KH: ['116', "Cambodia"],
  CM: ['120', "Cameroon"],
  CA: ['124', "Canada"],
  CV: ['132', "Cape Verde"],
  KY: ['136', "Cayman Islands"],
  CF: ['140', "Central African Republic"],
  TD: ['148', "Chad"],
  CL: ['152', "Chile"],
  CN: ['156', "People's Republic of China"],
  CX: ['162', "Christmas Island"],
  CC: ['166', "Cocos (Keeling) Islands"],
  CO: ['170', "Colombia"],
  KM: ['174', "Comoros"],
  CG: ['178', "Republic of the Congo"],
  CD: ['180', "Democratic Republic of the Congo"],
  CK: ['184', "Cook Islands"],
  CR: ['188', "Costa Rica"],
  CI: ['384', "Cote d'Ivoire"],
  HR: ['191', "Croatia"],
  CU: ['192', "Cuba"],
  CY: ['196', "Cyprus"],
  CZ: ['203', "Czech Republic"],
  DK: ['208', "Denmark"],
  DJ: ['262', "Djibouti"],
  DM: ['212', "Dominica"],
  DO: ['214', "Dominican Republic"],
  EC: ['218', "Ecuador"],
  EG: ['818', "Egypt"],
  SV: ['222', "El Salvador"],
  GQ: ['226', "Equatorial Guinea"],
  ER: ['232', "Eritrea"],
  EE: ['233', "Estonia"],
  ET: ['231', "Ethiopia"],
  FK: ['238', "Falkland Islands (Malvinas)"],
  FO: ['234', "Faroe Islands"],
  FJ: ['242', "Fiji"],
  FI: ['246', "Finland"],
  FR: ['250', "France"],
  GF: ['254', "French Guiana"],
  PF: ['258', "French Polynesia"],
  TF: ['260', "French Southern Territories"],
  GA: ['266', "Gabon"],
  GM: ['270', "Republic of The Gambia"],
  GE: ['268', "Georgia"],
  DE: ['276', "Germany"],
  GH: ['288', "Ghana"],
  GI: ['292', "Gibraltar"],
  GR: ['300', "Greece"],
  GL: ['304', "Greenland"],
  GD: ['308', "Grenada"],
  GP: ['312', "Guadeloupe"],
  GU: ['316', "Guam"],
  GT: ['320', "Guatemala"],
  GN: ['324', "Guinea"],
  GW: ['624', "Guinea-Bissau"],
  GY: ['328', "Guyana"],
  HT: ['332', "Haiti"],
  HM: ['334', "Heard Island and McDonald Islands"],
  VA: ['336', "Holy See (Vatican City State)"],
  HN: ['340', "Honduras"],
  HK: ['344', "Hong Kong"],
  HU: ['348', "Hungary"],
  IS: ['352', "Iceland"],
  IN: ['356', "India"],
  ID: ['360', "Indonesia"],
  IR: ['364', "Islamic Republic of Iran"],
  IQ: ['368', "Iraq"],
  IE: ['372', "Ireland"],
  IL: ['376', "Israel"],
  IT: ['380', "Italy"],
  JM: ['388', "Jamaica"],
  JP: ['392', "Japan"],
  JO: ['400', "Jordan"],
  KZ: ['398', "Kazakhstan"],
  KE: ['404', "Kenya"],
  KI: ['296', "Kiribati"],
  KP: ['408', "North Korea"],
  KR: ['410', "South Korea"],
  KW: ['414', "Kuwait"],
  KG: ['417', "Kyrgyzstan"],
  LA: ['418', "Lao People's Democratic Republic"],
  LV: ['428', "Latvia"],
  LB: ['422', "Lebanon"],
  LS: ['426', "Lesotho"],
  LR: ['430', "Liberia"],
  LY: ['434', "Libya"],
  LI: ['438', "Liechtenstein"],
  LT: ['440', "Lithuania"],
  LU: ['442', "Luxembourg"],
  MO: ['446', "Macao"],
  MG: ['450', "Madagascar"],
  MW: ['454', "Malawi"],
  MY: ['458', "Malaysia"],
  MV: ['462', "Maldives"],
  ML: ['466', "Mali"],
  MT: ['470', "Malta"],
  MH: ['584', "Marshall Islands"],
  MQ: ['474', "Martinique"],
  MR: ['478', "Mauritania"],
  MU: ['480', "Mauritius"],
  YT: ['175', "Mayotte"],
  MX: ['484', "Mexico"],
  FM: ['583', "Micronesia, Federated States of"],
  MD: ['498', "Moldova, Republic of"],
  MC: ['492', "Monaco"],
  MN: ['496', "Mongolia"],
  MS: ['500', "Montserrat"],
  MA: ['504', "Morocco"],
  MZ: ['508', "Mozambique"],
  MM: ['104', "Myanmar"],
  NA: ['516', "Namibia"],
  NR: ['520', "Nauru"],
  NP: ['524', "Nepal"],
  NL: ['528', "Netherlands"],
  NC: ['540', "New Caledonia"],
  NZ: ['554', "New Zealand"],
  NI: ['558', "Nicaragua"],
  NE: ['562', "Niger"],
  NG: ['566', "Nigeria"],
  NU: ['570', "Niue"],
  NF: ['574', "Norfolk Island"],
  MP: ['580', "Northern Mariana Islands"],
  MK: ['807', "The Republic of North Macedonia"],
  NO: ['578', "Norway"],
  OM: ['512', "Oman"],
  PK: ['586', "Pakistan"],
  PW: ['585', "Palau"],
  PS: ['275', "State of Palestine"],
  PA: ['591', "Panama"],
  PG: ['598', "Papua New Guinea"],
  PY: ['600', "Paraguay"],
  PE: ['604', "Peru"],
  PH: ['608', "Philippines"],
  PN: ['612', "Pitcairn"],
  PL: ['616', "Poland"],
  PT: ['620', "Portugal"],
  PR: ['630', "Puerto Rico"],
  QA: ['634', "Qatar"],
  RE: ['638', "Reunion"],
  RO: ['642', "Romania"],
  RU: ['643', "Russian Federation"],
  RW: ['646', "Rwanda"],
  SH: ['654', "Saint Helena"],
  KN: ['659', "Saint Kitts and Nevis"],
  LC: ['662', "Saint Lucia"],
  PM: ['666', "Saint Pierre and Miquelon"],
  VC: ['670', "Saint Vincent and the Grenadines"],
  WS: ['882', "Samoa"],
  SM: ['674', "San Marino"],
  ST: ['678', "Sao Tome and Principe"],
  SA: ['682', "Saudi Arabia"],
  SN: ['686', "Senegal"],
  SC: ['690', "Seychelles"],
  SL: ['694', "Sierra Leone"],
  SG: ['702', "Singapore"],
  SK: ['703', "Slovakia"],
  SI: ['705', "Slovenia"],
  SB: ['090', "Solomon Islands"],
  SO: ['706', "Somalia"],
  ZA: ['710', "South Africa"],
  GS: ['239', "South Georgia and the South Sandwich Islands"],
  ES: ['724', "Spain"],
  LK: ['144', "Sri Lanka"],
  SD: ['729', "Sudan"],
  SR: ['740', "Suriname"],
  SJ: ['744', "Svalbard and Jan Mayen"],
  SZ: ['748', "Eswatini"],
  SE: ['752', "Sweden"],
  CH: ['756', "Switzerland"],
  SY: ['760', "Syrian Arab Republic"],
  TW: ['158', "Taiwan, Province of China"],
  TJ: ['762', "Tajikistan"],
  TZ: ['834', "United Republic of Tanzania"],
  TH: ['764', "Thailand"],
  TL: ['626', "Timor-Leste"],
  TG: ['768', "Togo"],
  TK: ['772', "Tokelau"],
  TO: ['776', "Tonga"],
  TT: ['780', "Trinidad and Tobago"],
  TN: ['788', "Tunisia"],
  TR: ['792', "Türkiye"],
  TM: ['795', "Turkmenistan"],
  TC: ['796', "Turks and Caicos Islands"],
  TV: ['798', "Tuvalu"],
  UG: ['800', "Uganda"],
  UA: ['804', "Ukraine"],
  AE: ['784', "United Arab Emirates"],
  GB: ['826', "United Kingdom"],
  US: ['840', "United States of America"],
  UM: ['581', "United States Minor Outlying Islands"],
  UY: ['858', "Uruguay"],
  UZ: ['860', "Uzbekistan"],
  VU: ['548', "Vanuatu"],
  VE: ['862', "Venezuela"],
  VN: ['704', "Vietnam"],
  VG: ['092', "Virgin Islands, British"],
  VI: ['850', "Virgin Islands, U.S."],
  WF: ['876', "Wallis and Futuna"],
  EH: ['732', "Western Sahara"],
  YE: ['887', "Yemen"],
  ZM: ['894', "Zambia"],
  ZW: ['716', "Zimbabwe"],
  AX: ['248', "Åland Islands"],
  BQ: ['535', "Bonaire, Sint Eustatius and Saba"],
  CW: ['531', "Curaçao"],
  GG: ['831', "Guernsey"],
  IM: ['833', "Isle of Man"],
  JE: ['832', "Jersey"],
  ME: ['499', "Montenegro"],
  BL: ['652', "Saint Barthélemy"],
  MF: ['663', "Saint Martin (French part)"],
  RS: ['688', "Serbia"],
  SX: ['534', "Sint Maarten (Dutch part)"],
  SS: ['728', "South Sudan"],
  XK: ['983', "Kosovo"],
};

/** Numeric-3 id -> English country name (reverse index for map tooltips). */
export const ISO_NUMERIC_NAME: Record<string, string> = Object.fromEntries(
  Object.values(ISO_A2).map(([n, name]) => [n, name]),
);
