#!/usr/bin/env node
// Forwards live Stripe webhook events to the local dev server during
// `bun run dev`. Without this, events only ever reach the production endpoint
// registered in the Stripe dashboard, so local checkout/payment flows never
// fire `checkout.session.completed`, `invoice.payment_*`, `payout.*`, etc.
//
// What it does:
//   1. Reads the Stripe CLI's device-stable local webhook signing secret
//      (`stripe listen --print-secret`) and writes it to `.env.stripe.local`.
//      The server loads that file with `override` in development (see
//      server/src/lib/env.ts) so the LOCAL secret wins over the production
//      STRIPE_WEBHOOK_SECRET in the root .env — signature verification matches
//      the forwarded events. The server's `tsx watch` watches that file and
//      restarts automatically once it's written.
//   2. Runs `stripe listen --forward-to localhost:4000/webhooks/stripe`.
//
// Resilient by design: if the Stripe CLI is missing, not logged in, or its API
// key is expired (`stripe login` needed), it logs a warning and IDLES instead
// of exiting — otherwise concurrently's kill-others flag (-k) would tear down
// the whole dev stack just because Stripe forwarding isn't available.

import { spawn, spawnSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const ENV_FILE = resolve(here, '../.env.stripe.local');
const FORWARD_TO = 'localhost:4000/webhooks/stripe';
// Allow pointing at a non-PATH binary if needed (e.g. STRIPE_CLI_PATH=C:\src\stripe\stripe.exe).
// Quoted so a path with spaces survives shell invocation.
const STRIPE = `"${process.env.STRIPE_CLI_PATH || 'stripe'}"`;

function idle(reason) {
  console.warn(`[stripe-listen] ${reason}`);
  console.warn(
    '[stripe-listen] Local webhook forwarding is OFF. Run `stripe login` to refresh the CLI key, then restart `bun run dev`.',
  );
  // Keep this process alive so concurrently -k does not kill the dev stack.
  setInterval(() => {}, 1 << 30);
}

function writeStripeEnv(secret) {
  const body =
    '# Auto-generated by scripts/stripe-listen.mjs — local Stripe CLI webhook signing\n' +
    '# secret. Loaded (with override) only in development. Do NOT commit.\n' +
    `STRIPE_WEBHOOK_SECRET=${secret}\n`;
  writeFileSync(ENV_FILE, body, 'utf8');
}

// 1. Confirm the CLI is present.
const version = spawnSync(`${STRIPE} --version`, { encoding: 'utf8', shell: true });
if (version.status !== 0) {
  idle('Stripe CLI not found on PATH (set STRIPE_CLI_PATH or install from https://stripe.com/docs/stripe-cli).');
} else {
  // 2. Fetch the local webhook signing secret (same one `stripe listen` uses).
  const secretRes = spawnSync(`${STRIPE} listen --print-secret`, { encoding: 'utf8', shell: true });
  const secret = `${secretRes.stdout ?? ''}`.trim().match(/whsec_[A-Za-z0-9]+/)?.[0];
  if (!secret) {
    const detail = `${secretRes.stderr ?? secretRes.stdout ?? ''}`.trim().split('\n')[0];
    idle(`Could not read the local webhook secret${detail ? ` (${detail})` : ''}.`);
  } else {
    writeStripeEnv(secret);
    console.log('[stripe-listen] Wrote local STRIPE_WEBHOOK_SECRET → .env.stripe.local');
    console.log(`[stripe-listen] Forwarding Stripe events → ${FORWARD_TO}`);
    // 3. Forward live events to the local webhook endpoint.
    const child = spawn(`${STRIPE} listen --forward-to ${FORWARD_TO}`, {
      stdio: 'inherit',
      shell: true,
    });
    child.on('exit', (code) => idle(`\`stripe listen\` exited (code ${code}).`));
    // Forward termination signals so Ctrl-C cleans the child up too.
    for (const sig of ['SIGINT', 'SIGTERM']) {
      process.on(sig, () => {
        child.kill();
        process.exit(0);
      });
    }
  }
}
