import { useEffect, useRef } from 'react';
import { useLocation } from 'wouter';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { ArrowRight, Heart, Loader2, RefreshCw } from 'lucide-react';
import { toast } from 'sonner';
import { useTRPC } from '@shared/lib/trpc';
import { PageHeader, PigmentButton, InkButton } from '../components/primitives';
import { SvgMark } from '../components/SvgMark';
import { DirectionPreview, type PreviewConcept } from '../components/DirectionPreview';
import { useStudio } from '../app/studio-context';

type Concept = PreviewConcept;

export function Concepts() {
  const [, navigate] = useLocation();
  const trpc = useTRPC();
  const qc = useQueryClient();
  const { projectId, selectedId, setSelectedId, overview } = useStudio();

  const listQuery = useQuery(
    trpc.logo.concepts.list.queryOptions({ projectId: projectId! }, { enabled: !!projectId }),
  );
  const concepts = (listQuery.data ?? []) as Concept[];

  const invalidate = () =>
    qc.invalidateQueries({ queryKey: trpc.logo.concepts.list.queryKey({ projectId: projectId! }) });

  const generate = useMutation(trpc.logo.concepts.generate.mutationOptions());
  const toggleSave = useMutation(trpc.logo.concepts.toggleSave.mutationOptions());
  const choose = useMutation(trpc.logo.concepts.choose.mutationOptions());

  const hasBrief = !!overview.data?.project?.brief;

  // Auto-generate the first sheet when we arrive with a brief but no concepts.
  // Guarded to ONCE per project: a round that yields nothing usable would
  // otherwise satisfy this condition again and bill another generation on every
  // re-render. After the first attempt the user drives it with Regenerate.
  const autoGenerated = useRef<string | null>(null);
  useEffect(() => {
    if (!projectId || !hasBrief) return;
    if (autoGenerated.current === projectId) return;
    if (listQuery.isSuccess && concepts.length === 0 && !generate.isPending) {
      autoGenerated.current = projectId;
      generate.mutate(
        { projectId, count: 6 },
        { onSuccess: () => invalidate(), onError: (e) => toast.error(e.message) },
      );
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [projectId, hasBrief, listQuery.isSuccess, concepts.length]);

  const generateMore = () => {
    if (!projectId) return;
    generate.mutate(
      { projectId, count: 6, avoid: concepts.map((c) => c.note || c.name).slice(0, 12) },
      { onSuccess: () => invalidate(), onError: (e) => toast.error(e.message) },
    );
  };

  const onToggleSave = (c: Concept) => {
    setSelectedId(c.id);
    toggleSave.mutate({ generationId: c.id, saved: !c.saved }, { onSuccess: () => invalidate() });
  };

  const onChoose = (c: Concept) => {
    if (!projectId || choose.isPending) return;
    setSelectedId(c.id);
    choose.mutate(
      { projectId, generationId: c.id },
      {
        onSuccess: () => {
          qc.invalidateQueries({ queryKey: trpc.logo.overview.queryKey() });
          navigate('/studio');
        },
        onError: (e) => toast.error(e.message),
      },
    );
  };

  const sel = concepts.find((c) => c.id === selectedId) ?? null;
  const generating = generate.isPending;

  if (!hasBrief && !concepts.length) {
    return (
      <div className="mx-auto max-w-[1120px] px-4 pb-24 pt-8 sm:px-6 lg:px-8 lg:pt-10">
        <PageHeader index="02" eyebrow="Concepts" title="No brief yet." lede="Start with a brief so the studio knows the brand's character." />
        <PigmentButton className="mt-8" onClick={() => navigate('/create')}>
          Start the brief <ArrowRight className="h-4 w-4" />
        </PigmentButton>
      </div>
    );
  }

  return (
    <div className="mx-auto max-w-[1280px] px-4 pb-24 pt-8 sm:px-6 lg:px-8 lg:pt-10">
      <PageHeader
        index="02"
        eyebrow="Concepts"
        title="Directions."
        lede="Every mark is an editable vector, drawn in black and white so the form has to earn it. Pick one to see it in place — or push the studio for more."
        action={
          <InkButton onClick={generateMore}>
            {generating ? <Loader2 className="h-4 w-4 animate-spin" /> : <RefreshCw className="h-4 w-4" />}
            Regenerate
          </InkButton>
        }
      />

      {/* contact sheet + the selected direction, seen in place */}
      <div className="mt-9 grid grid-cols-1 items-start gap-6 lg:grid-cols-[minmax(0,1fr)_340px] lg:gap-7">
        <div className="grid min-w-0 grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-3">
          {listQuery.isLoading || (generating && !concepts.length)
            ? Array.from({ length: 6 }).map((_, i) => <SkeletonCard key={i} />)
            : concepts.map((c, i) => (
                <ConceptCard
                  key={c.id}
                  concept={c}
                  index={i}
                  selected={selectedId === c.id}
                  committing={choose.isPending && selectedId === c.id}
                  // First press previews it in the panel; pressing the direction
                  // you're already looking at commits it to the editor.
                  onSelect={() => (selectedId === c.id ? onChoose(c) : setSelectedId(c.id))}
                  onLike={() => onToggleSave(c)}
                />
              ))}

          {!!concepts.length && (
            <button
              onClick={generateMore}
              className="concept flex min-h-[280px] flex-col items-center justify-center gap-3 rounded-[var(--radius-lg)] border border-dashed border-[var(--hair-2)] bg-transparent text-[var(--ink-3)] hover:border-[var(--pigment)] hover:text-[var(--pigment)]"
            >
              <span className="grid h-12 w-12 place-items-center rounded-full border border-current">
                {generating ? <Loader2 className="h-5 w-5 animate-spin" /> : <RefreshCw className="h-5 w-5" />}
              </span>
              <span className="text-sm font-semibold">Generate six more</span>
              <span className="spec" style={{ fontSize: 10 }}>
                Free · keeps your brief
              </span>
            </button>
          )}
        </div>

        {/* Sticky beside the sheet, and self-scrolling on short viewports so the
            specimens never push the commit button out of reach. */}
        <div className="min-w-0 lg:sticky lg:top-[4.5rem] lg:max-h-[calc(100vh-6rem)] lg:overflow-y-auto">
          <DirectionPreview
            concept={sel}
            wordmarkFallback={overview.data?.project?.brief?.businessName ?? overview.data?.brandName ?? ''}
            onChoose={() => sel && onChoose(sel)}
            onToggleSave={() => sel && onToggleSave(sel)}
            choosing={choose.isPending}
          />
        </div>
      </div>
    </div>
  );
}

function ConceptCard({
  concept,
  index,
  selected,
  committing = false,
  onSelect,
  onLike,
}: {
  concept: Concept;
  index: number;
  selected: boolean;
  /** The commit is in flight — this card is on its way to the editor. */
  committing?: boolean;
  onSelect: () => void;
  onLike: () => void;
}) {
  const score = concept.uniqueness ?? 0;
  return (
    <div
      role="button"
      tabIndex={0}
      onClick={onSelect}
      onKeyDown={(e) => (e.key === 'Enter' || e.key === ' ') && onSelect()}
      data-selected={selected}
      aria-label={
        selected ? `Refine ${concept.name} in the editor` : `Preview the ${concept.name} direction`
      }
      className="concept group relative cursor-pointer overflow-hidden rounded-[var(--radius-lg)] border border-[var(--hair-2)] bg-[var(--card)]"
    >
      <div className="specimen stage-grid grid h-[220px] place-items-center border-x-0 border-t-0">
        <SvgMark svg={concept.svg} tone={selected ? 'pigment' : 'ink'} animate className="h-24 w-24" title={concept.name} />
        <span className="spec absolute left-4 top-4" style={{ fontSize: 10 }}>
          {String(index + 1).padStart(2, '0')}
        </span>
        <button
          onClick={(e) => {
            e.stopPropagation();
            onLike();
          }}
          className="press absolute right-3 top-3 grid h-8 w-8 place-items-center rounded-full border border-[var(--hair-2)] bg-[var(--card)] transition"
          aria-label="Save concept"
        >
          <Heart
            className="h-4 w-4"
            style={{ color: concept.saved ? 'var(--pigment)' : 'var(--ink-3)', fill: concept.saved ? 'var(--pigment)' : 'none' }}
          />
        </button>

        {/* The selected card's second press commits — say so, or it's invisible. */}
        {selected && (
          <span
            className="spec pop absolute inset-x-0 bottom-0 flex items-center justify-center gap-1.5 bg-[var(--pigment)] py-1.5"
            style={{ fontSize: 9, color: '#fff' }}
          >
            {committing ? (
              <>
                <Loader2 className="h-3 w-3 animate-spin" /> Opening editor
              </>
            ) : (
              <>
                Press again to refine <ArrowRight className="h-3 w-3" />
              </>
            )}
          </span>
        )}
      </div>

      <div className="flex items-center justify-between gap-3 px-4 py-3.5">
        <div className="min-w-0">
          <p className="truncate text-sm font-semibold text-[var(--ink)]">{concept.name}</p>
          <p className="truncate text-xs text-[var(--ink-3)]">{concept.note}</p>
        </div>
        <div className="shrink-0 text-right">
          <div className="spec tnum" style={{ color: 'var(--ink)' }}>
            {score}
          </div>
          <div className="mt-1 h-1 w-12 overflow-hidden rounded-full bg-[var(--hair-2)]">
            <div className="h-full rounded-full" style={{ width: `${score}%`, background: 'var(--pigment)' }} />
          </div>
        </div>
      </div>
    </div>
  );
}

function SkeletonCard() {
  return (
    <div className="overflow-hidden rounded-[var(--radius-lg)] border border-[var(--hair-2)] bg-[var(--card)]">
      <div className="stage-grid grid h-[220px] place-items-center">
        <Loader2 className="h-6 w-6 animate-spin text-[var(--ink-3)]" />
      </div>
      <div className="px-4 py-3.5">
        <div className="h-4 w-24 rounded bg-[var(--hair-2)]" />
        <div className="mt-2 h-3 w-32 rounded bg-[var(--hair)]" />
      </div>
    </div>
  );
}
